### ISSUE TITLE
MATLAB built-in `decomposition` vs SuiteSparse `factorize`

### ISSUE THREAD

**Issue by briochemc** [DrTimothyAldenDavis/SuiteSparse#113]
Are they the same? Are there cases where one would rather (install SuiteSparse and) use `factorize` instead of `decomposition`?

**Comment by DrTimothyAldenDavis** [comment]
They aren't the same.  I haven't benchmarked them.  I wrote my factorize method first, and proposed it to MathWorks.  They wrote their own, based on my ideas, as the new decomposition method.  I don't know which is faster or has more features, however.

**Comment by DrTimothyAldenDavis** [comment]
Thanks for the feedback.

The built-in decomposition method is using calls to internal methods (most of which are mine, such as UMFPACK, CHOLMOD, and SuiteSparseQR).  The internal methods return my factorization in a format that is not a MATLAB sparse matrix, but my own format, and these are faster to use for my subsequent solve phases.  That explains why the built-in decomposition is faster than factorize.m.   I don't have access to this feature in factorize.m, so I have to return the factors back to MATLAB as vanilla MATLAB sparse matrices (inside the factorization object). 

This is also the reason the MATLAB decomposition is more accurate.  UMFPACK is used by both decomposition and factorize.  My built-in UMFPACK forward/backward solver has a iterative refinement step with sparse backward error analysis.  The decomposition method can use this since they keep the factors in the UMFPACK format.  I don't have access to that from a MATLAB m-file, so my forward/backsolves in the factorizat method can't make use of my iterative refinement inside UMFPACK.

So the only reason these methods differ is because MathWorks doesn't provide end-users access to these internal features.  Otherwise, these methods would be identical, since they use the same underlying methods.

The statement xBS = M\y uses UMFPACK with my iterative refinement step enabled, which is why it gets the same accuracy as the decomposition method.

I do have a method that can exploit block diagonal matrices, and also permuted versions.  The built-in dmperm is my code, from CSparse, with MathWorks uses for dmperm.  My KLU solver exploits this, but not UMFPACK, CHOLMOD, or SPQR.  KLU isn't a built-in method in MATLAB however.  I could use it inside factorize but you'd have to install KLU first, and I wanted to make factorize.m a stand-alone package.

**Comment by briochemc** [comment]
Thank you for all the insightful details!

**Comment by DrTimothyAldenDavis** [comment]
I forgot to mention why the run times are different.  In factorize.m, I have to call lu, and get back MATLAB sparse matrices.  The lu method uses UMFPACK internally, but it takes me more work to translate my internal format into the vanilla MATLAB sparse matrices when it returns.  I use lu in factorize.m.  That step is skipped by decomposition.m, which can keep my factorization in its original UMFPACK format.
