### ISSUE TITLE
Question about compressed-column representation

### ISSUE THREAD

**Issue by szhorvat** [DrTimothyAldenDavis/SuiteSparse#129]
I hope that this is not an inappropriate place to ask this question.

When using the CXSparse library, and using a compressed-column representation, is it guaranteed that explicit (non-null) matrix elements are stored in order of increasing row index (for each column)?

**Comment by DrTimothyAldenDavis** [comment]
No, the CSparse/CXSparse library can return a CSC matrix with unsorted columns.  In the MATLAB interface, I sort them before returning them to MATLAB, using cs_transpose (which has the side effect of sorting the indices).  MATLAB requires the CSC format to have sorted columns (increasing row index in each column).  The only thing I guarantee is factorizations place the diagonal element as the first entry in each column of L, for example, or last entry for U or R.  This is so that the triangular solvers can find the diagonals.

**Comment by szhorvat** [comment]
I forgot to respond here originally. Thank you for the prompt reply, it saved us a lot of time!
