### ISSUE TITLE
mongoose: unconditional coverage flags

### ISSUE THREAD

**Issue by xantares** [DrTimothyAldenDavis/SuiteSparse#217]
mongoose unconditionally uses coverage flags:
```
SET(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} -fprofile-arcs -ftest-coverage")
SET(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -fprofile-arcs -ftest-coverage")
SET(CMAKE_EXE_LINKER_FLAGS_DEBUG "-fprofile-arcs -ftest-coverage")
...
set_target_properties(mongoose_lib_dbg PROPERTIES COMPILE_FLAGS "${CMAKE_CXX_FLAGS_DEBUG}")
set_target_properties(mongoose_lib_dbg PROPERTIES LINK_FLAGS "${CMAKE_EXE_LINKER_FLAGS_DEBUG}")
```

this is not desired in release mode

upstream mongoose has an ENABLE_COVERAGE option to disable coverage flags:
https://github.com/ScottKolo/Mongoose/commit/433f0a9188682d6cffc2ede92463a5b8648a1f33

```
option(ENABLE_COVERAGE "Enable coverage flags" ON)
...
    if (ENABLE_COVERAGE)
      SET(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} -fprofile-arcs -ftest-coverage")
      SET(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -fprofile-arcs -ftest-coverage")
      SET(CMAKE_EXE_LINKER_FLAGS_DEBUG "-fprofile-arcs -ftest-coverage")
    endif ()
```

and on mingw this would also allow to avoid undefined references to the coverage lib:
```
/usr/lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld: CMakeFiles/mongoose_lib_dbg.dir/objects.a(Mongoose_BoundaryHeap.obj):/tmp/sp/src/SuiteSparse-6.0.2/Mongoose/Source/Mongoose_BoundaryHeap.cpp:206: undefined reference to `__gcov_exit'
```

**Comment by DrTimothyAldenDavis** [comment]
Good point.  I didn't realize that was in there.  I did it slightly differently than Scott's version.  The environment variable and cmake variable is called `MONGOOSE_COVERAGE`.

Try the latest version on dev2, with this change: https://github.com/DrTimothyAldenDavis/SuiteSparse/commit/592b40a5ae3d389806fb61a1daef6305587c599c

I haven't tagged it as a pre-release, like v6.0.3.beta, since all I changed was the Mongoose/CMakeLists.txt file.  Can you give this a try on mingw?

**Comment by xantares** [comment]
great, i've tested it defaults to off so thats ok for me, thanks
