### ISSUE TITLE
NOPENBLAS not working?

### ISSUE THREAD

**Issue by Fabian188** [DrTimothyAldenDavis/SuiteSparse#223]
Edit: Deleted as I somehow might have done something wrong. I cannot reproduce.

**Comment by DrTimothyAldenDavis** [comment]
Probably what happened was that SuiteSparse_config was compiled first, and then NOPENMP disabled openmp.

SuiteSparse_config uses the NOPENMP flag because it has a SuiteSparse_time function.  That function uses omp_get_wtime if openmp is available.  Otherwise it uses system-specific methods.

If you then recompiled SuiteSparse_config with NOPEMP as ON, the problem would go away.  So that's probably what happened.
