### ISSUE TITLE
Confusing behaviour of AMD v/s CAMD

### ISSUE THREAD

**Issue by sandwichmaker** [DrTimothyAldenDavis/SuiteSparse#311]
Let me give a brief overview of the behavior I am observing and if it is found to be unexpected, I will upload code and data that replicates it. 

My experiments are done with SuiteSparse 7.0.1 running on a mac installed via homebrew. Happy to share more details as needed.

I have a SPD matrix A which can be partitioned as follows

```
A =  [P  Q]
     [Q' R]
```

P is a diagonal matrix, and eventually I am interested in running CHOLMOD on the Schur complement matrix 

```
S = R - Q'inv(P) Q
```

I would like to order the columns of A. 

Now, I can do one of two things.

1. Since I know P is diagonal I can call cholmod_camd with the columns of P in set 0 and the columns of Q/R in set 1.
2. Compute the sparsity pattern of S and call cholmod_amd on S since the elimination order of the columns of P does not matter and will not affect the sparsity structure of S.

I expect that the ordering I get in both of these cases to be of the same quality. By that I mean, I expect that when using CAMD, the columns of P will be have some (it does not matter what) ordering, but the columns of Q/R should have the same ordering as running AMD on S. But this is not the case. 

To my surprise, CAMD consistently gives MUCH better orderings than AMD. By better here I mean that when I perform numerical factorization of S, it is considerably faster to use the ordering returned by CAMD than it is by AMD. This is reflected in the analysis phase where the flop count between the two cases can differ by an order of magnitude.

This is not limited to a single matrix either, I have multiple instances of these matrices where this happens.

Is my mental model for CAMD correct? or is this expected behavior, in which case I would like to understand why.

The reason this is of interest to me is because S is MUCH smaller than A, so running AMD on S is much faster (by an order of magnitude) than running CAMD on A.

**Comment by DrTimothyAldenDavis** [comment]
I'm not surprised to see the difference.  When inside either AMD or CAMD, I don't represent the matrix S in a flat form, but as a collection of original entries plus a set of cliques from the prior eliminations.  Then the degrees I keep are upper bounds on the exact degrees.  As a result, S is not the same.  AMD is starting with a flattened S with its exact degrees, but CAMD has a different representation of S (original edges plus the cliques) with upper bound degrees.

Both AMD and CAMD are heuristics that are trying to get a good permutation to reduce fillin, but they are seeing different problems in this case.  Once the problem is different, there's no certainty about which one will do better than the other.
