### ISSUE TITLE
the SuiteSparse package in homebrew is compiled without OpenMP and without TIMER (i.e. no SuiteSparse_tic)

### ISSUE THREAD

**Issue by freeseek** [DrTimothyAldenDavis/SuiteSparse#313]
When running a piece of software based on CHOLMOD with the [Homebrew SuiteSparse](https://github.com/Homebrew/homebrew-core/blob/master/Formula/suite-sparse.rb) package, I realized that the timer function was not enabled (no SuiteSparse_tic). After digging into it a bit, I believe that this is the result of the `SUITESPARSE_TIMER_ENABLED` macro not being enabled in [SuiteSparse_config.h](https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/dev/SuiteSparse_config/SuiteSparse_config.h):
```
#ifndef NTIMER
    #if defined ( _OPENMP )
        #define SUITESPARSE_TIMER_ENABLED
    #elif defined ( _POSIX_C_SOURCE )
        #if _POSIX_C_SOURCE >= 199309L
        #define SUITESPARSE_TIMER_ENABLED
        #endif
    #endif
#endif
```
This is because `brew` on Mac uses `clang` which does not define `_POSIX_C_SOURCE`. Also, the `brew` package version does not link to OpenMP. I filed a [bug](https://github.com/Homebrew/homebrew-core/issues/129011) with Homebrew but their understanding is that this is something that should be resolved in the SuiteSparse code, not in Homebrew. I wish I could be more helpful but I do not fully understand how options are selected at compilation time

**Comment by DrTimothyAldenDavis** [comment]
I can see what I can do to enable the timer, but disabling OpenMP for SuiteSparse is a mistake.  One of my recent packages (GraphBLAS) makes significant use of OpenMP, and disabling will slow GraphBLAS down by 20x or more on some systems.  Homebrew should use OpenMP with SuiteSparse.  SuiteSparse is using OpenMP for more than the timer.

The other packages (CHOLMOD, UMFPACK, SPQR) use a parallel BLAS, which normally also requires OpenMP.

The timing code is here:  https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/03350b0faef6b77d965ddb7c3cd3614a45376bfd/SuiteSparse_config/SuiteSparse_config.c#L438 .

Getting a timer to work in a portable manner is non-trivial (linux, mac, windows, different compilers, etc), which is why the default is to use the OpenMP timer if available, or the POSIX timer otherwise.

**Comment by DrTimothyAldenDavis** [comment]
I've tried to use the ANSI C clock function, that that causes problems too:  it's often not very accurate, and it is not always implemented in right way (see for example https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/clock?redirectedfrom=MSDN&view=msvc-170 ).  

Getting the timer to work well and in a portable manner has been a nightmare so I don't intend to change it.  The timer requires either OpenMP or POSIX, or it is disabled.  I can't change that.
