### ISSUE TITLE
dirty repo after building

### ISSUE THREAD

**Issue by sdirkse67** [DrTimothyAldenDavis/SuiteSparse#332]
After I do a make in the SuiteSparse_config dir on my Windows machine, the file `SuiteSparse_config.h` is modified.  This isn't a bug, but I mention it in case your intention is that the make system not dirty the repo.

You could avoid this by creating a copy of the file somewhere in the build dir and changing the copy.  Or some C preprocessor magic could do the job.

There are some other dirty files.  Here's my status after a full `make local`:

```
[nb@kermit ~/sdirkse/github/SuiteSparse/stable]$ git status 
On branch dev2
Your branch is up to date with 'origin/dev2'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   CXSparse/Include/cs.h
        modified:   GraphBLAS/Config/GB_config.h
        modified:   SuiteSparse_config/SuiteSparse_config.h

no changes added to commit (use "git add" and/or "git commit -a")

```

**Comment by DrTimothyAldenDavis** [comment]
These files are configured by cmake to match the particulars of the installation.

GraphBLAS/Config/GB_config.h is created from GraphBLAS/Config/GB_config.h.in, with lots of system-specific things.

It would be safe to add .gitignore for GraphBLAS/Config/GB_config.h, but the others need to be updated as version numbers change.  CXSparse/Include.cs.h includes a configured value, @CXSPARSE_USE_COMPLEX, which is 1 or 0 (see CXSparse/Config/cs.h.in).  I guess you had turned off complex numbers in CXSparse?

SuiteSparse_config/SuiteSparse_config.h is configured with the BLAS calling sequence, and the BLAS integer size, from SuiteSparse_config/Config/SuiteSparse_config.h.in.  I don't want to add it to .gitignore, though, because someone might want to compile these packages without cmake.

**Comment by DrTimothyAldenDavis** [comment]
The problem is that these *.h files are essential if someone tries to build these packages without cmake.  If I set them as .gitignored, then they might get out of sync in my repo.  If they are at least set to some reasonable defaults, then they can work and the codes can be compiled without cmake.

GB_config.h is special.  It has nothing else except system-specific stuff.  So it would be safe to .gitignore it.  But I can't do that with the others.  The downside is that the repo looks modified after a build but I don't know how to avoid that.

**Comment by sdirkse67** [comment]
Perhaps you could include the current versions of these files in the repo under a different name.  The cmake system could behave as it does currently, but the make system could copy the precursor files to the real thing if they didn't already exist or if they need to be refreshed.  For example, SuiteSparse_config.pre.h included in the repo,  and a Makefile rule 

```
SuiteSparse_config.h: SuiteSparse_config.pre.h
       cp $< $@
```

In this case you could .gitignore the files actually included, but the precursors would be in the repo in the usual way.

Please don't pursue this on my account: I am content as is.

**Comment by DrTimothyAldenDavis** [comment]
I would rather keep it simple and let git think the repo has been modified.  If someone creates a PR with the modified *_config.h files, they will get revised anyway the next time me or someone else compiles SuiteSparse.

**Comment by AnHeuermann** [comment]
In case anyone else finds this in the future wondering why git is always reporting a changed repository.
I have a *local* workaround to hide the changes inside my SuiteSparse submodule:

```bash
git -C SuiteSparse update-index --skip-worktree SuiteSparse_config/SuiteSparse_config.h
```

Updating my SuiteSparse submodule needs this to be deactivated again (at least if SuiteSparse_config.h changes).
Undo with:

```bash
git -C SuiteSparse update-index --no-skip-worktree SuiteSparse_config/SuiteSparse_config.h
```
