### ISSUE TITLE
UMFPACK  requires amd_internal.h

### ISSUE THREAD

**Issue by thierry-FreeBSD** [DrTimothyAldenDavis/SuiteSparse#408]
AMD does not install amd_internal.h (normal, since it is internal), but the compilation of UMFPACK fails without it:

```
[  0% 8/683] /usr/bin/cc -DBLAS_OpenBLAS -DUMFPACK_EXPORTS -I/usr/ports/math/suitesparse-umfpack/work/SuiteSparse-7.2.0/UMFPACK -I/usr/ports/math/suitesparse-umfpack/work/SuiteSparse-7.2.0/UMFPACK/Source -I/usr/ports/math/suitesparse-umfpack/work/SuiteSparse-7.2.0/UMFPACK/Include -isystem /usr/local/include/suitesparse -O2 -pipe  -O3 -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fopenmp=libomp  -O2 -pipe  -O3 -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -DNDEBUG -std=gnu11 -fPIC -MD -MT CMakeFiles/UMFPACK.dir/Source2/umf_di_dump.c.o -MF CMakeFiles/UMFPACK.dir/Source2/umf_di_dump.c.o.d -o CMakeFiles/UMFPACK.dir/Source2/umf_di_dump.c.o -c /usr/ports/math/suitesparse-umfpack/work/SuiteSparse-7.2.0/UMFPACK/Source2/umf_di_dump.c
FAILED: CMakeFiles/UMFPACK.dir/Source2/umf_di_dump.c.o 
/usr/bin/cc -DBLAS_OpenBLAS -DUMFPACK_EXPORTS -I/usr/ports/math/suitesparse-umfpack/work/SuiteSparse-7.2.0/UMFPACK -I/usr/ports/math/suitesparse-umfpack/work/SuiteSparse-7.2.0/UMFPACK/Source -I/usr/ports/math/suitesparse-umfpack/work/SuiteSparse-7.2.0/UMFPACK/Include -isystem /usr/local/include/suitesparse -O2 -pipe  -O3 -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fopenmp=libomp  -O2 -pipe  -O3 -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -DNDEBUG -std=gnu11 -fPIC -MD -MT CMakeFiles/UMFPACK.dir/Source2/umf_di_dump.c.o -MF CMakeFiles/UMFPACK.dir/Source2/umf_di_dump.c.o.d -o CMakeFiles/UMFPACK.dir/Source2/umf_di_dump.c.o -c /usr/ports/math/suitesparse-umfpack/work/SuiteSparse-7.2.0/UMFPACK/Source2/umf_di_dump.c
In file included from /usr/ports/math/suitesparse-umfpack/work/SuiteSparse-7.2.0/UMFPACK/Source2/umf_di_dump.c:10:
In file included from /usr/ports/math/suitesparse-umfpack/work/SuiteSparse-7.2.0/UMFPACK/Source/umf_dump.c:14:
/usr/ports/math/suitesparse-umfpack/work/SuiteSparse-7.2.0/UMFPACK/Source/umf_internal.h:95:10: fatal error: 'amd_internal.h' file not found
#include "amd_internal.h"
         ^~~~~~~~~~~~~~~~
1 error generated.
```

Context: UMFPACK 6.2.0 included in v7.2.0.

**Comment by mmuetzel** [comment]
That is odd indeed. (But not the only place where a SuiteSparse subproject uses internal headers from another SuiteSparse project. Maybe, they aren't meant to be standalone projects?)

A work-around would probably be to first build AMD and after that build UMFPACK in the same source tree... (Untested though)

**Comment by mmuetzel** [comment]
Turns out some of the sources of the different libraries of SuiteSparse are interdependent. (See https://github.com/DrTimothyAldenDavis/SuiteSparse/issues/175#issuecomment-1722554769.)
It's probably best to use the top-level Makefile to get that interdependency right...

**Comment by DrTimothyAldenDavis** [comment]
This would be an easy fix:  I would just place an exact copy of AMD/Include/amd_internal.h in the UMFPACK/Source folder, and likely for the other places I do this (GPUQREngine and SuiteSparseGPURuntime, for example).

I can probably take care of this before I have to step away from the keyboard for awhile (likely Sept 20 to 30th).

**Comment by mmuetzel** [comment]
Maybe, a symlink would also be enough?

That way the risk of those files inadvertently diverging would be lower.

**Comment by DrTimothyAldenDavis** [comment]
symlinks are dicey.  They can break on different OS's.

I can add a script that does a diff of any duplicated files, as a precaution.  I'm not too worried about that risk.

All I need to do is "chmod 000 *" in my SuiteSparse folder, then open up one package at a time, build it, and install it, then chmod 000 that folder again.  Then repeat that for each package, in order that they appear in the top-level Makefile.  That way, if UMFPACK tries to build, it will only find the installed libamd.so and amd.h, not amd_internal.h or any other files.

This way, I should be able to detect any files that are currently sneaking in.

Shouldn't take long to fix.

**Comment by DrTimothyAldenDavis** [comment]
oh .. easier said than done.  Each of the CMakeLists.txt looks for the cmake modules it depends on, and they aren't found in SuiteSparse/lib, or in /usr/local/lib/cmake.  They are found inside the SuiteSparse source folder itself.  So if I "chmod 000" the directories, they cmake config scripts aren't found -- even though they appear both in SuiteSparse/lib (via "make local; make install") and in /usr/local/lib/cmake (via "make; make install").

How do I get the cmake build system for each package to prefer finding the installed package, in find_package, so I can check for these file dependencies like amd_internal.h?

**Comment by thierry-FreeBSD** [comment]
I built every module separately in order to upgrade the FreeBSD packages, and I only encountered this failure with UMFPACK.

**Comment by mmuetzel** [comment]
> How do I get the cmake build system for each package to prefer finding the installed package, in find_package, so I can check for these file dependencies like amd_internal.h?

Maybe, you'd need to purge the `build` folders after building and installing each project separately. If there is nothing, it can't be found. 😉

**Comment by DrTimothyAldenDavis** [comment]
> I built every module separately in order to upgrade the FreeBSD packages, and I only encountered this failure with UMFPACK.

You would also find an error if you enabled CUDA, since the GPUQREngine package includes SuiteSparseGPU_internal.hpp, which is not installed, and which also #includes many other files that are private to the SuiteSparseGPU_Runtime package.

Another place that an error might occur is the test coverage for CHOLMOD, since the code in CHOLMOD/Tcov includes amd_internal.h and camd_internal.h.

**Comment by DrTimothyAldenDavis** [comment]
I did a "make local ; make install ; make purge" for SuiteSparse_config, and then "make local" for AMD, but AMD couldn't find the SuiteSparse_configConfig.cmake file.

**Comment by mmuetzel** [comment]
~~Where did you install the library? `make purge` also deletes the `local` install target.~~

Maybe, you'd need to set `-DCMAKE_PREFIX_PATH="/installation/prefix/lib/cmake"` (with the correct installation prefix) if you installed somewhere that isn't searched by default...

**Comment by DrTimothyAldenDavis** [comment]
I tried that, but it still didn't find them.

Anway, I think I've fixed the problem.  @thierry-FreeBSD, can you try the latest dev2 branch?

I have these two commits.  

One for UMFPACK:
https://github.com/DrTimothyAldenDavis/SuiteSparse/commit/f3c9f8dd35e2520dc990d7e1829daf5d3e39d764

and another for GPUQREngine (which #include's internal files in SuiteSparse_GPURuntime/Include):
https://github.com/DrTimothyAldenDavis/SuiteSparse/commit/c2e4820adc6e53da4930ff31c0ab54b03073899a

This is a short-term fix, but I can release this as SuiteSparse v7.2.1 if this works for you.  UMFPACK would become v6.2.1 and GPUQREngine would bump to v3.2.1.

For the long term, I will do something more elegant.  In particular, I need to refactor UMFPACK, CHOLMOD, and SPQR, because I plan on adding support for single precision floating point values (both real and complex).  When I do that, I will revise my strategy, and avoid using internal include files from one library in another.

For SuiteSparse_GPURuntime and GPUQREngine:  these two libraries should probably be folded into the SPQR_CUDA library anyway.  That would be simpler.

**Comment by thierry-FreeBSD** [comment]
This is fine for UMFPACK!

But I never tried to compile GPUQREngine (no GPU here).

Another idea (for a later release, no hurry): maybe move the parts used for other modules from amd_internal.h to the installable header?

**Comment by DrTimothyAldenDavis** [comment]
Sounds good.  The change to GPUQREngine should also work fine (it works for me, with GPUs and cuda enabled).

> Another idea (for a later release, no hurry): maybe move the parts used for other modules from amd_internal.h to the installable header?

That would break user's codes since amd_internal.h defines things like TRUE, FALSE, MAX, MIN, and so on.  I use those in UMFPACK, but it would cause lots of chaos in user applications that use UMFPACK and AMD since those definitions breaks out of  the "AMD_*" namespace.

**Comment by DrTimothyAldenDavis** [comment]
I'll go ahead and post a v7.2.1.beta release of SuiteSparse with this fix.

**Comment by DrTimothyAldenDavis** [comment]
Thanks again for catching this.
