### ISSUE TITLE
amd_internal.h is not installed but it is used by umfpack

### ISSUE THREAD

**Issue by kiwifb** [DrTimothyAldenDavis/SuiteSparse#417]
I cannot build umfpack-6.2.1 for Gentoo when I create a system package.
```
FAILED: CMakeFiles/UMFPACK.dir/Source2/umf_di_assemble_fixq.c.o 
/usr/bin/x86_64-pc-linux-gnu-gcc -DBLAS_Intel10_64lp -DUMFPACK_EXPORTS -I/home/portage/sci-libs/umfpack-6.2.1/work/SuiteSparse-7.2.0/UMFPACK_build -I/home/portage/sci-libs/umfpack-6.2.1/work/SuiteSparse-7.2.0/UMFPACK -I/home/portage/sci-libs/umfpack-6.2.1/work/SuiteSparse-7.2.0/UMFPACK/Source -I/home/portage/sci-libs/umfpack-6.2.1/work/SuiteSparse-7.2.0/UMFPACK/Include  -O2 -pipe -fopenmp  -std=gnu11 -fPIC -MD -MT CMakeFiles/UMFPACK.dir/Source2/umf_di_assemble_fixq.c.o -MF CMakeFiles/UMFPACK.dir/Source2/umf_di_assemble_fixq.c.o.d -o CMakeFiles/UMFPACK.dir/Source2/umf_di_assemble_fixq.c.o -c /home/portage/sci-libs/umfpack-6.2.1/work/SuiteSparse-7.2.0/UMFPACK/Source2/umf_di_assemble_fixq.c
In file included from /home/portage/sci-libs/umfpack-6.2.1/work/SuiteSparse-7.2.0/UMFPACK/Source/umf_assemble.c:14,
                 from /home/portage/sci-libs/umfpack-6.2.1/work/SuiteSparse-7.2.0/UMFPACK/Source2/umf_di_assemble_fixq.c:11:
/home/portage/sci-libs/umfpack-6.2.1/work/SuiteSparse-7.2.0/UMFPACK/Source/umf_internal.h:95:10: fatal error: amd_internal.h: No such file or directory
   95 | #include "amd_internal.h"
      |          ^~~~~~~~~~~~~~~~
```
If that header is to be used, it should be installed properly.

**Comment by kiwifb** [comment]
I see there is also a `camd_internal.h` that can be used if you compile stuff in `CHOLMOD/Tcov`.

**Comment by DrTimothyAldenDavis** [comment]
I just fixed that in the draft SuiteSparse 7.2.1: https://github.com/DrTimothyAldenDavis/SuiteSparse/issues/408
https://github.com/DrTimothyAldenDavis/SuiteSparse/pull/416/commits/f3c9f8dd35e2520dc990d7e1829daf5d3e39d764

Can you try the dev2 branch?  This is a pending PR to the dev branch (I'm waiting for the CI to finish before merging it into the default dev branch).

**Comment by DrTimothyAldenDavis** [comment]
I'm aware about camd_internal.h but I've left it as-is.  The test coverage doesn't work unless CHOLMOD appears side-by-side with AMD, CAMD, etc, and it doesn't get installed.  It doesn't even have a cmake build script, just a simple Makefile.

**Comment by kiwifb** [comment]
> I'm aware about camd_internal.h but I've left it as-is. The test coverage doesn't work unless CHOLMOD appears side-by-side with AMD, CAMD, etc, and it doesn't get installed. It doesn't even have a cmake build script, just a simple Makefile.

I just grepped for where amd_internal.h was used to see if that could tell me something more about its management, and camd_internal.h showed up. But it is very much of the flavor, "if it is intended to be used by other things, then it should be shipped".

**Comment by DrTimothyAldenDavis** [comment]
Actually, the fix is already in the dev branch, so you might just need a git pull.

Other than Tcov tests, the only place amd_internal.h is used is in UMFPACK, and it contains stuff that shouldn't be shipped ("#define TRUE 1, #define MAX ..." etc).  It's only meant for internal use, in just AMD and UMFPACK.  But as you point out, amd_internal.h isn't found unless AMD and UMFPACK are side-by-side in the SuiteSparse source tree, so I need to either (a) install amd_internal.h for everyone (not a good idea), (b) copy the file into UMFPACK (a short-term fix), or (c) rework the definitions so UMFPACK doesn't actually need amd_internaly.  The latter is in progress but (b) should fix it for now.

The Tcov scripts for all my packages aren't meant to be installed, and they only work if all the packages are side-by-side in the SuiteSparse top-level folder.  The `*/Tcov/Makefiles` do lots of things with source code from other directories.  The UMFPACK Tcov Makefile compiles all of `../AMD/Source/*.c`, in particular, all by itself, without using -lamd.

The same is true for CHOLMOD/Tcov.

So I don't need to fix those.  It wouldn't be possible to build the Tcov tests at all as stand-alone builds.

amd_internal.h is another story, and it should be fixed now, in both the dev and dev2 branches (but not yet fixed in the stable branch.

**Comment by DrTimothyAldenDavis** [comment]
I also plan on including this PR in SuiteSparse 7.2.1:  https://github.com/DrTimothyAldenDavis/SuiteSparse/pull/410 once the tests finish.

I'll then post a SuiteSparse v7.2.1.beta1, which hopefully will fix this issue.

**Comment by kiwifb** [comment]
OK LGTM.

**Comment by DrTimothyAldenDavis** [comment]
Great!  Sorry for the confusion ... you caught me in the middle of fixing it, so I'm glad it works after all.

**Comment by DrTimothyAldenDavis** [comment]
I'll leave this open until I post 7.2.1 as a stable release, in case someone else has the same issue.

**Comment by DrTimothyAldenDavis** [comment]
https://github.com/DrTimothyAldenDavis/SuiteSparse/releases/tag/v7.2.1 is now posted as a stable release.
