### ISSUE TITLE
Julia solution results different from SuiteSparse C library

### ISSUE THREAD

**Issue by DragonPara** [DrTimothyAldenDavis/SuiteSparse#492]
julia 1.9.3
C:  
+ gcc 4.8.5 
+ SuiteSparse 7.2.2 && SuiteSparse 5.2

julia code:
```julia
A = SuiteSparse.SparseArrays.SparseMatrixCSC(ncols,ncols,Ap,Ai,Ax)
F = lu(A)
X = F \ B
```
c code
```c
umfpack_di_symbolic(n_row, n_col, Ap, Ai, Ax, &Symbolic, null, null);
umfpack_di_numeric(Ap, Ai, Ax, Symbolic, &Numeric, null, null);
umfpack_di_solve(UMFPACK_A, Ap, Ai, Ax, X, B, Numeric, null, null);
umfpack_di_free_symbolic(&Symbolic);
umfpack_di_free_numeric(&Numeric);
```
They will get different answers. Did I choose the wrong C function？

**Comment by DrTimothyAldenDavis** [comment]
It's hard to say because I don't know what goes on inside F=lu(A) in julia.   For example, does the julia interface enable any scaling of the input matrix?  Does it do any iterative refinement or not?  umfpack has an iterative refinement method for example.  Is julia enabling it?  What ordering options are being used?

There's also no output of status values, residuals, Info status results like umfpack_di_report_status, and so on.  You have passed in NULL for the Info result so there's no Info to go by.

You have n_row, ncol for the C code, but ncols,ncols for the julia code.  Is the matrix square?

How different are the solutions?

There's no enough information to go by to answer your question.
