### ISSUE TITLE
t_cholmod_super_numeric.c bug ???

### ISSUE THREAD

**Issue by AEArtemyev** [DrTimothyAldenDavis/SuiteSparse#517]
In the CHOLMOD/Supernodal/t_cholmod_super_numeric.c file, should line number 423 have the variable pf instead of p?

**Comment by DrTimothyAldenDavis** [comment]
Yes, that's a bug.  Thanks for the catch!  I suppose I only test this partcular code with a "packed" F matrix, so that the 2nd clause of that ternary is never used.  In the released version:

https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/8627b9c4423188230e0fa7c46f32a3abb3f77405/CHOLMOD/Supernodal/t_cholmod_super_numeric.c#L422-L423

And this bug also appears in my latest branch, singledev2:

https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/b0f841580b1505ead8de05e4856a5598b38130b7/CHOLMOD/Supernodal/t_cholmod_super_numeric_worker.c#L436-L437

I will fix it there on singledev2 shortly.

**Comment by DrTimothyAldenDavis** [comment]
Those 2 lines of code are a common way I traverse a sparse packed/unpacked matrix in CHOLMOD.  I'll have to check the other places I do that.  I'll also add the "unpacked F" case to my test suite, which would have caught this bug.

I'll leave this issue open until I post CHOLMOD 5.1.0 with this fix (and also with the new single-precision sparse matrix support).

**Comment by DrTimothyAldenDavis** [comment]
Thanks for catching this.  This is now fixed in SuiteSparse 7.4.0, in the default dev branch of the SuiteSparse repo.  I'll release a 7.4.0.beta1 soon.
