### ISSUE TITLE
CHOLMOD: retrieve number of non-zeros in a factor

### ISSUE THREAD

**Issue by jakub-homola** [DrTimothyAldenDavis/SuiteSparse#523]
How can I find the number of non-zeros in a `cholmod_factor`, which contains only symbolic factorization, but not numeric?

I need to know the nnz after `cholmod_analyze`, but before calling `cholmod_factorize`.

I cannot use `cholmod_factor_to_sparse` and then extract the nnz from there, because the factor is only symbolic at that time, so not convertible to sparse yet.

The closest I found is `print_factor`, but the nnz is printed, but I need it returned to use it in other code. Furthermore, for simplical factors it seems to always print 0.

**Comment by jakub-homola** [comment]
So I looked inside the `print_factor` function and tried to extract the way it calculates the nnz.

Assuming that supernodal factorization is used (forced with `Common->supernodal = CHOLMOD_SUPERNODAL`), would whis be a correct implementation?

```
template<typename Int>
Int my_cholmod_factor_get_nnz(cholmod_factor * L)
{
    Int lnz = 0;

    if(L->is_super)
    {
        Int * Lpi = (Int*)L->pi ;
        Int * Super = (Int*)L->super ;

        for (Int s = 0 ; s < L->nsuper ; s++)
        {
            Int k1 = Super [s] ;
            Int k2 = Super [s+1] ;
            Int psi = Lpi [s] ;
            Int psend = Lpi [s+1] ;
            Int nsrow = psend - psi ;
            Int nscol = k2 - k1 ;

            lnz += nscol * nsrow - (nscol*nscol - nscol)/2 ;
        }
    }
    else
    {
        fprintf(stderr, "only supernodal is supported\n");
        lnz = -1;
    }

    return lnz;
}
```

**Comment by DrTimothyAldenDavis** [comment]
The simplest place to get it is Common->lnz, if you want it for statistics or for a heuristic test.  

If you have subsequently made another call to cholmod_analyze, it may overwrite Common->lnz, so you can query L itself.

If you need the exact size of the supernodal factorization, after relaxed supernodal amalgamation, then you can use L->xsize.  The exact size of the simplicial factorization is L->nzmax.  Those values appear in the symbolic factorization L.

So this would do both cases:

`nzmax = L->is_super ? L->xsize : L->nzmax ;
`
For example, I use this when converting the symbolic L to the numeric L (simplicial or supernodal):
https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/8627b9c4423188230e0fa7c46f32a3abb3f77405/CHOLMOD/Utility/t_cholmod_change_xdtype.c#L216

**Comment by DrTimothyAldenDavis** [comment]
I could add this as a new function in CHOLMOD, say `cholmod_factor_nnz (cholmod_factor *L, cholmod_common *cm)`.

After checking its inputs to make sure L is valid, it would just have that single line of code.  Perhaps `cholmod_factor_nzmax` would be a better name, because both values can be upper bounds on the actual # of entries in L.    For the simplicial case, L can be revised with update/downdates, and L->nzmax can have empty space in it if entries have been removed from a downdate.  For the supernodal case, the "true" number of entries in L is the same as the simplicial factors, but the supernodes can have explicit zeros in them because of relaxed amalgamation.

Either that, or I could just add an explanation to the User Guide, to use the expression:
 `nzmax = L->is_super ? L->xsize : L->nzmax`
and explain that the tight # of nonzeros in L can be less than this number.

The exact number for a supernodal factor is computed here, which I think matches your code, just a different expression:

https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/8627b9c4423188230e0fa7c46f32a3abb3f77405/CHOLMOD/Utility/t_cholmod_change_factor.c#L910-L972

And for the simplicial factor, it would be:
```
lnz = 0 ;
for (j = 0 ; j < n ; j++) { lnz += Lnz [j] ; }
```

So if I wrote a cholmod_factor_nnz, it would have the above lengthy code.  If I wrote a cholmod_factor_nzmax, it would be just a one-liner.

**Comment by DrTimothyAldenDavis** [comment]
For a sparse Cholesky factorization, there are at least 4, and perhaps 6 ways to define "# of nonzeros in L".  In increasing order of size (but 3 and 4 are not in any order):

(1) the number of entries not numerically equal to zero.  This is a bit ephemeral since it's affected by roundoff, denormals flushing to zero, and so on, but it's <= any of (2) to (5) below.

(2) the number of entries in the filled graph of L.  This is a very stable number, and doesn't depend on roundoff, data structures, or factorization method used.  It only depends on the symbolic pattern of A, and the fill-reducing ordering. Some entries can be exactly zero because of roundoff but this is ignored.  I return this as Common->lnz but I don't save this statistic in L itself (that would be handy, but it would be out of date if update/downdates occur).

(3) the number of entries in the supernodal L, which is like (2) but with added entries because of relaxed amalgamation.  This affected by everything in (2), but also the relaxed amalgamation parameters. This could be split into (3a) and (3b), where (3a) excludes entries in the upper triangular part of each supernoded.  The (3a) definition is computed in the for loop above.

(4) the number of entries in L after any update/downdates.  A downdate can delete entries but I don't keep track of when this happens. I would need to keep L as a collection of multisets, and update/downdate the multiplicity of each entry.  I actually did this for a while but it's costly.  So instead I have a cholmod_resymbol method to prune these down to (2).  This number is sum(Lnz[0..n-1]).

(5) the size of the data structure to hold the entries of L.  That's L->xsize and L->nzmax.  For a supernodal L, L->xsize treats each supernode as rectangular, not lower trapezoidal.  For a simplicial L, after update/downdate, I can include gaps in the columns of L to allow for room for growth.

Which one do you want :-) ?

So it gets complicated.  It's a great question to ask, though.  I don't have methods to compute these numbers, except for Common->lnz, and the simple expression `(L->is_super ? L->xsize : L->nzmax)` if you can count that.

I will add a discussion to this effect in the User Guide.

**Comment by DrTimothyAldenDavis** [comment]
See subsection 15.12 in my draft User Guide for CHOLMOD 5.1.0, in https://github.com/DrTimothyAldenDavis/SuiteSparse/tree/singledev2
and specifically this commit:
https://github.com/DrTimothyAldenDavis/SuiteSparse/commit/0dc844e58b31a4b72721062aa454129fbae9aed6

**Comment by jakub-homola** [comment]
Thanks for the insightful replies. I did not expect it would be that complicated :)

In my use case, I need the nnz to preallocate memory in my own data structures on a GPU, which I will be filling up with the factor converted to sparse matrix:
1. `cholmod_analyze`
2. get nnz of the factor
3. preallocate memory in my own sparse matrix data structure on a GPU, depending on the nnz of the factor
4. `cholmod_factorize`
5. `cholmod_factor_to_sparse`
6. copy the `cholmod_sparse` matrix to my own sparse matrix structure on a GPU
7. do something with the GPU factor

The steps 4-7 will be repeated multiple times for the same pattern of the matrix I am factorizing, so it makes sense to preallocate memory for the factor.

So, what I need is the maximum nnz which could be in the sparse matrix containing the factor, obtained from `cholmod_factor_to_sparse`. This probably corresponds to number (2).

I perform the factorizations in parallel, I have a `cholmod_common` object for every matrix I am factorizing, so the `Common->lnz` seems perfect for me.

This fully answers my questions, I think I can close this issue.

Thank you.

**Comment by DrTimothyAldenDavis** [comment]
If L is supernodal, then I think (2) is smaller than what you need.  You need (3) to get the # of entries in the sparse matrix L.  This is because converting a supernodal L to a sparse matrix keeps the entries added due to relaxed supernodal amalgamation.

So I would suggest that you need this:

nzmax = L->is_super ? L->xsize : L->nzmax ; 

You aren't doing update/downdates, so this number will be very tight.

**Comment by jakub-homola** [comment]
Alright, thanks :)

**Comment by DrTimothyAldenDavis** [comment]
Alternatively, if you followed your step (1) by a conversion of L to simplicial via cholmod_change_factor, then do cholmod_resymbol, that process will remove the entries included because of relaxed supernodal amalgamation.  It will keep the graph of L chordal, which is very helpful to any subsequent Cholesky factorization: the etree still works, the pattern of the rows of L can be found via traversing the etree (see the SUBTREE macro in cholmod_rowfac), the first offdiagonal entry in L(:,j) is the parent of j in the etree, update/downdates can be done, etc.

Those properties are also preserved in the supernodal L, but with cholmod_resymbol, they can be tightened up, and the memory usage and subsequent flop count on the GPU would be reduced a bit.

The alternative is cholmod_drop, after L becomes a sparse matrix, but that's not a good idea.  It breaks all those nice properties, and it's also unpredictable because of variations in roundoff can give you either a value of 1e-20, or zero, say.
