### ISSUE TITLE
SLIP LU userguide not rebuilt by "make docs"

### ISSUE THREAD

**Issue by svillemot** [DrTimothyAldenDavis/SuiteSparse#53]
Hi,

I’ve noticed that the SLIP LU userguide is not rebuilt by top-level "make docs", as for the other libraries.

Is that an overlook?

Thanks for your work,

**Comment by DrTimothyAldenDavis** [comment]
Thanks -- that's an oversight.  I'll add it.

**Comment by DrTimothyAldenDavis** [comment]
This is fixed in the SPEX package (replaces SLIP_LU) in the beta SuiteSparse v6.0.0.

I've also put in an entirely new build system for all of SuiteSparse ... it's now all CMake.  I do have a simple top-level Makefile remaining, only because I find this process tedious:

`mkdir build ; cd build ; cmake .. ; make`

That works (although I already have placed an empty build/ folder in each package), and it's done by the top-level 'make'.
