### ISSUE TITLE
License inconsistency for CHOLMOD/Include

### ISSUE THREAD

**Issue by svillemot** [DrTimothyAldenDavis/SuiteSparse#697]
The `LICENSE.txt` at the root of the repository states that `CHOLMOD/Include` is under the LGPL. But inside those four headers, it is said that they are under the Apache 2.0 license.

So there is some inconsistency that needs to be fixed.

Incidentally, `cholmod.h` lacks an `SPDX-License-Identifier` entry.

**Comment by DrTimothyAldenDavis** [comment]
cholmod.h is an odd file.  I used to have individual headers for each CHOLMOD module, but that's annoying to have in a linux distro so I went with a single cholmod.h file.  But then that single cholmod.h header has files from Modules with different licenses: LGPL and GPL.

So I'm reluctant to add an SPEX-License-Identifier since it might be confused as to being the license for all of CHOLMOD.

I can fix the LICENSE.txt file though.

I should probably stick with LGPL-2 for cholmod.h, since CHOLMOD is otherwise just two licenses: some LGPL and some GPL.  That might be simpler.

**Comment by DrTimothyAldenDavis** [comment]
On 2nd thought, I'll leave them as Apache-2.0, because of this discussion, which I want to preserve:

https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/6c2d12b24005bc6fae9d2de6c3115844b76695b4/CHOLMOD/Include/cholmod.h#L23-L33

I'll just revise the LICENSE.txt file to say Apache-2.0, and also add more clarification, with this commit to the dev2 branch: https://github.com/DrTimothyAldenDavis/SuiteSparse/commit/06adfc0126c44bc4bfd1d92f7367dce90c521166

Thanks for catching this glitch.

Does this look clear now?

**Comment by svillemot** [comment]
Thanks, the proposed commit addresses my concerns.
