### ISSUE TITLE
Versions in release notes

### ISSUE THREAD

**Issue by szhorvat** [DrTimothyAldenDavis/SuiteSparse#711]
1. I'd like to request to include all version number increases in the release notes. 7.5.0.beta3 seems to have this, but 7.4.0 does not. This is useful because all packages are distributed in a single archive, but many package managers make them installable separately. Package maintainers then have to check each CMakeLists.txt file to see if there was a version update.

2. I wanted to point out that the 7.5.0.beta3 release notes indicate LDL 3.1.1. This should be 3.3.1 instead.

**Comment by DrTimothyAldenDavis** [comment]
That's a good idea. I should probably add a top-level SuiteSparse/Release_Notes.txt file (or .md) that I keep up to date with a list of the latest versions of each package.  As you can see with the LDL typo, I can make mistakes with that.  Then when I make a release, I can cut-and-paste that Release_Notes.txt as the release notes for that release.

**Comment by DrTimothyAldenDavis** [comment]
> 2\. I wanted to point out that the 7.5.0.beta3 release notes indicate LDL 3.1.1. This should be 3.3.1 instead.

I've fixed that just now, as well.

**Comment by DrTimothyAldenDavis** [comment]
Rather than adding a new file, I will just include this list in the SuiteSparse/ChangeLog.  Then I will simply cut-and-paste that as the Release Notes for 7.5.0.beta5.

https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/d5582da8af7fc7c1cdd86e160e99f58b3394e845/ChangeLog#L1-L34

and likewise for future releases.  Thanks for the suggestion.
