### ISSUE TITLE
CSparse matrix elements as 'double'

### ISSUE THREAD

**Issue by ngc1052** [DrTimothyAldenDavis/SuiteSparse#74]
Is there any particular reason why the matrix elements of a csi type defined in cs.h, CSparse are hardcoded as double? I'm planning to use your sparse matrix implementation to solve a memory intense problem but with double occupying 8 bytes on my machine, I'm running out of memory, float would be much better. Would there be any unwanted consequences of rewriting all doubles to floats?

**Comment by DrTimothyAldenDavis** [comment]
double is essential in the general case, since many sparse matrix problems can be very ill-conditioned.  CSparse would need both float and double.  But since CSparse is meant to be a terse, concise package, it only supports one type, and thus I selected double.  Float could be added to CXSparse, the extended version of the package, but not CSparse.
