### ISSUE TITLE
operational zero and indefiniteness in simplical LL factorization

### ISSUE THREAD

**Issue by ghost** [DrTimothyAldenDavis/SuiteSparse#76]
Hi there,

I recently tried to use cholmod to detect linear dependencies in large sparse matrices which were build from cross-product of a linear model design matrix X, e.g. C=X'X. For the test case I knew about the location of the linear dependencies. However, cholmod did not flag C as indefinite. Only after norming C by diag(1/diag(C))%*%C%*%diag(1/diag(C)) and subsequently dividing it by 100000 cholmod reported the trouble-causing rows/columns in C correctly.

My hunch is that due to the large numbers in C, which were initially integers, the rounding errors during factorization prohibit flagging C as not pd as. This is because it appears as if routine "Cholesky/t_cholmod_rowfac.c line: 430" will only flag if the diagonal element of the factor becomes zero, where zero is literally zero.

As a suggestion it might be useful to add an entry to cholmod_common which defines the operational zero, which can be overwitten by the user, and which serves as a comparison in function cholmod_is_zero.

all the best.

**Comment by DrTimothyAldenDavis** [comment]
I understand the issue, but properly detecting indefinite or singular matrices is much harder than just checking for small values.  That's why I just check for exact zeros.  The concern would be setting this value correctly.  In addition, it would only apply to the simplicial case, not the supernodal case, so I'd get different results depending on which method I use.  The two methods are selected automatically, so this could lead to very bizarre and unpredictable behavior.  A better solution would be a condition estimator.

**Comment by kalle0** [comment]
Hi

thanks for your response.

I certainly understand the danger of allowing the user to set the operational zero. But it would add flexibility and could be initialised with zero anyway.

With regard to the method selection I am aware that supernodal wouldn't help me. But I understand the manual page 54

`If Common->supernodal <= CHOLMOD_SIMPLICIAL (0) then cholmod_analyze performs a simplicial analysis`

that when I set `common->supernodal=zero` I can enforce using simplical analysis. In line, I understand that, setting `common->supernodal=1` and `common->supernodal_switch=0.0` should enforce super-nodal. Please correct me if I am wrong.

The matrix X described above might be +100k columns and several million rows, so C would be +100k x +100k. I am not sure whether a condition number can be obtained in a timely manner and whether that condition number would point me to the column in X to be omitted.

There exist many adhoc approaches to make X full rank which seem to all come with their own pitfall. I have added opzero to a local copy of the 5.8.1 version and so far I am very happy with the ability to find the precise columns to omit.

**Comment by DrTimothyAldenDavis** [comment]
Yes, it is possible to force CHOLMOD to do a non-supernodal factorization.

The Supernodal factorization can't check the diagonal, or take corrective
action, since I call LAPACK to do the Cholesky factorization of the
leading part of each supernode.  I can't modify that to look for zeros or
epsilons.
