### ISSUE TITLE
GraphBLAS 9.3.0 stuck at linking time on Linux aarch64

### ISSUE THREAD

**Issue by brunvonlope** [DrTimothyAldenDavis/SuiteSparse#862]
**Describe the bug**
Trying to build suitesparse 7.8.0 makes the linker be in a frozen state. Last lines were:

```
/run/build/SuiteSparse/GraphBLAS/JITpackage/Source/grb_jitpackage.c:18:32: warning: unknown warning group '-Wstringop-overflow', ignored [-Wunknown-warning-option]
   18 | #pragma GCC diagnostic ignored "-Wstringop-overflow"
      |                                ^
/run/build/SuiteSparse/GraphBLAS/JITpackage/Source/grb_jitpackage.c:151:21: warning: result of comparison of constant -1 with expression of type 'char' is always true [-Wtautological-constant-out-of-range-compare]
  151 |         } while (ch != EOF);
      |                  ~~ ^  ~~~
2 warnings generated.
[2241/3238] Linking C executable GraphBLAS/JITpackage/grb_jitpackage
```

Nothing happens after the last line.

**To Reproduce**
Create a MR (like [this one](https://github.com/flathub/org.gimp.GIMP/pull/340)) trying to build GIMP beta flatpak updating suitesparse module to 7.8.0, this will trigger x64 and aarch64 builds.

Don't need to be GIMP to be honest, trying to build suitesparse 7.8.0 alone on Linux aarch64 should be enough.

**Expected behavior**
suitesparse builds (like 7.7.0)

**Desktop (please complete the following information):**
 - OS: Linux
 - compiler Clang 18
 - BLAS and LAPACK library: OpenBLAS 0.3.28
 - Version: 7.8.0

**Comment by DrTimothyAldenDavis** [comment]
I just noticed that a few days ago. I think I have a fix posted on the dev2 branch. I'll post an update shortly.

**Comment by mmuetzel** [comment]
Is the buildbot cross-compiling (e g., on x86_64 for aarch64) when building the package for aarch64? I'm asking because different build rules are used if it were. 

On second thought. @DrTimothyAldenDavis's change might have fixed a potentially infinite loop:
https://github.com/DrTimothyAldenDavis/SuiteSparse/commit/052852304a6be95f9d2c471e2d8faeb5ebe7961a

**Comment by brunvonlope** [comment]
@mmuetzel Probably no. According to flatpak-buider docs, cross-compiling is not supported.

**Comment by DrTimothyAldenDavis** [comment]
It’s the return value of fgetc. It needs to be an int. I just found this
occurring on a power8 system.

**Comment by DrTimothyAldenDavis** [comment]
I'm getting ready to release SuiteSparse 7.8.1 with this fix (GraphBLAS 9.3.1).  See https://github.com/DrTimothyAldenDavis/SuiteSparse/pull/863

There was a bug in grb_jitpackage.c, where "char ch = fgetc(...)" was typecasting from the int return value of fgetc to a char.  Then the char ch was compared with EOF, which is an int equal to -1.  The comparison was between a char (perhaps unsigned uint8_t?) and an int equal to -1.  I'm guessing the result of that comparison was technically undefined in the ANSI C Standard, because it works on most systems but failed on my Power8 system (which I caught last week).  I think you're seeing the same error I saw.

I will post a beta SuiteSparse 7.8.1 with this fix shortly (with this #863 pull request).

**Comment by DrTimothyAldenDavis** [comment]
Can you try v7.8.1.beta1?  See https://github.com/DrTimothyAldenDavis/SuiteSparse/releases/tag/v7.8.1.beta1 .  That should fix this issue.

**Comment by brunvonlope** [comment]
@DrTimothyAldenDavis Have done a build and can confirm that the bug is gone in 7.8.1 (beta 1). Closing as fixed.

**Comment by DrTimothyAldenDavis** [comment]
Great!  I'll post this as a stable 7.8.1 release shortly.
