### ISSUE TITLE
Incorporating a patch for building shared libraries that we carry in Julia

### ISSUE THREAD

**Issue by ViralBShah** [DrTimothyAldenDavis/SuiteSparse#90]
We would love to incorporate these two patches into SuiteSparse if possible, which we apply when we build it for Julia:

As discussed in https://github.com/JuliaLang/julia/issues/37323, this patch that makes it possible for us to build shared libraries:
https://github.com/JuliaLang/julia/blob/master/deps/patches/SuiteSparse-shlib.patch

If these can be accepted, I am happy to make a PR.

[VS EDIT: I had originally linked 2 patches - but I removed one of them which is no longer required]

**Comment by DrTimothyAldenDavis** [comment]
Yes, I can take a look.  Do the updates work on any system?  I'm not
familiar with the $$ORIGIN usage.  What does that do?

Can you sign my contributor agreement and send it to me?  I need that for
any patch or PR to be added to any code in SuiteSparse.

**Comment by ViralBShah** [comment]
@DrTimothyAldenDavis I have signed and sent the agreement to you.

@staticfloat Do you know what the $$ORIGIN stuff in our SuiteSparse patches is about? Does it have to do with the rpath stuff?

**Comment by staticfloat** [comment]
The `$$ORIGIN` patch is to set relative paths for `RPATH` lookups.  So, for instance, when `libsuitesparse.so` wants to look up `libgfortran.so.5` it can specify the dependency path as `$$ORIGIN/libgfortran.so.5` and that will look in the folder where `libsuitesparse.so` itself is sitting.  This allows for a relocatable installation instead of requiring absolute paths that won't translate well to another machine.

`$$ORIGIN` only works on ELF platforms, so Linux and FreeBSD.

**Comment by DrTimothyAldenDavis** [comment]
Thanks for the info.  I'll test out this patch and add it to v5.10.2.

**Comment by DrTimothyAldenDavis** [comment]
Can you make it a PR?
